### ISSUE TITLE
do you have any plan for adding sasonline support to library

### ISSUE THREAD

**Issue by isnehalkiran** [TheHardeep/kronos#1]
hi
incredible work on this library sir
do you have any plan to add sasonline support to list of brokers
 here is api doc for the sasonline
https://drive.google.com/file/d/15HMf1ieewe2FgHxZJ-YIGeDtyNVEgCQ2/view?usp=sharing

unofficial python library for sasonline
https://github.com/algo2t/alphatrade

btw how to contact you
do you have discord or telegram or whatsup??

thank you for awersome work

**Comment by TheHardeep** [comment]
I could add it for sure, although the API seems similar to mastertrust which is already in the library. If you can provide me an account I could test the API and add it as well.

**Comment by isnehalkiran** [comment]
account means - sasonine account??

**Comment by TheHardeep** [comment]
Yes, just for testing the API.

**Comment by isnehalkiran** [comment]
that is my primary trading account - i am using tradetron with it . so it is not usable for testing - i can test, if you show me how to test the code - i can install python and run some code on my pc.

**Comment by TheHardeep** [comment]
Great, then I will add the broker in my spare time and then you can test it.
